### ISSUE TITLE
App crash on start api 21

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/dhis2-android-datacapture#103]
869-869 W/System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
869-869 W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
869-869 W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
869-869 W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.output.FileOutput.openFile(FileOutput.java:67)
869-869 W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.output.FileOutput.startup(FileOutput.java:49)
869-869 W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.Agent.startup(Agent.java:122)
869-869 W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.Agent.getInstance(Agent.java:50)
869-869 W/System.err:     at org.jacoco.agent.rt.internal_b0d6a23.Offline.<clinit>(Offline.java:31)
869-869 W/System.err:     at org.dhis2.mobile.WorkService.$jacocoInit(WorkService.java)
869-869 W/System.err:     at org.dhis2.mobile.WorkService.<clinit>(WorkService.java)
869-869 W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
869-869 W/System.err:     at java.lang.Class.newInstance(Class.java:1572)
869-869 W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2713)
869-869 W/System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:144)
869-869 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
869-869 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
869-869 W/System.err:     at android.os.Looper.loop(Looper.java:135)
869-869 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5221)
869-869 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
869-869 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
869-869 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
869-869 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
869-869 W/System.err: Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
869-869 W/System.err:     at libcore.io.Posix.open(Native Method)
869-869 W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
869-869 W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
869-869 W/System.err: 	... 20 more
869-869 I/WorkService: onCreate()
869-869 I/WorkService: Service started
869-889 I/WorkService: loginUser
869-889 I/GET: https://play.dhis2.org/android-previous2/api/me/user-account
869-889 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa300000171 in tid 889 (pool-1-thread-1)

**Comment by idelcano** [comment]
The problem is here: A/libc: Fatal signal 11  Calling the method: https://github.com/EyeSeeTea/dhis2-android-datacapture/blob/master/dhis2-android-app/src/main/java/org/dhis2/mobile/network/HTTPClient.java#L69

I think is a bug with the Api 21, and windows SO. I didn't find solutions.

**Comment by idelcano** [comment]
@xurxodev test it in api 21 in Mac and works fine. I will move to invalid this isssue.
