### ISSUE TITLE
Crash saving dataset

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/dhis2-android-datacapture#99]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.dhis2.mobile.io.models.Form.isFieldCombinationRequired()' on a null object reference
                                                                      at org.dhis2.mobile.ui.activities.DataEntryActivity.upload(DataEntryActivity.java:385)
                                                                      at org.dhis2.mobile.ui.activities.DataEntryActivity.access$000(DataEntryActivity.java:59)
                                                                      at org.dhis2.mobile.ui.activities.DataEntryActivity$2.onClick(DataEntryActivity.java:265)
                                                                      at android.view.View.performClick(View.java:5637)
                                                                      at android.view.View$PerformClick.run(View.java:22429)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by idelcano** [comment]
I think this was solved in the last release. this bug happend when the currentForm was null.
